import { StyleSheet } from "react-native";

const Styles = StyleSheet.create({
  login_container: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    backgroundColor: "#ffd9c0",
  },
  ccontainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "70%",
    height: "60%",
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    overflow: "hidden",
  },
  left: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    flexGrow: 2,
    color: "#fff",
    fontSize: 48,
    fontWeight: "600",
  },
  right: {
    color: "#3f3f3f",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    flexGrow: 2,
  },
  image: {
    width: 112,
    height: 112,
    borderRadius: 56,
    resizeMode: "cover",
    marginBottom: 32,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  form_container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    height: "100%",
    width: "90%",
    borderRadius: 10,
  },
  loginbtn: {
    width: "56%",
    height: 40,
    borderRadius: 20,
    borderWidth: 0,
    marginVertical: 10,
    paddingHorizontal: 10,
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: "#8c006d",
    marginTop: 20,
  },
  input: {
    borderWidth: 2,
    borderColor: "#e8e8e8",
    padding: 15,
    borderRadius: 50,
    backgroundColor: "#353535",
    color: "#e8e8e8",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    width: 150,
    height: 40,
    marginBottom: 20,
  },
});

export default Styles;
